"""Backend configuration and safety limits."""

MAX_PROBLEM_LENGTH = 4000
MAX_VARIABLES = 8
MAX_EXPRESSION_LENGTH = 2000
MAX_DONT_CARE_CONDITIONS = 8
GEMINI_TIMEOUT_SECONDS = 30
MAX_RETRIES = 1

# Image upload limits for /api/analyze-circuit-image.
MAX_IMAGE_BYTES = 10 * 1024 * 1024
MAX_IMAGE_PIXELS = 40_000_000
